version: 2.1

# Load Styra's cli orb
orbs:
  styra-orb: styra/cli@dev:0.0.1

workflows:
  version: 2.1
  check-workflow:
    jobs:
    - styra-orb/styra-check:
        context: test
        api_token : ${TOKEN}