version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: styra/cli # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run:
        name: Configure
        command: styra-cli configure -i test.styra.com -t ${TOKEN}
    - run:
        name: Validate
        command: styra-cli validate check-local -r ${CIRCLE_WORKING_DIRECTORY}


workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: test 
