version: 2.1

description: orb test

orbs:
  styra-orb:
    executors:
      cli:
        docker:
          - image: styra/cli
    commands:
      cli-check:
        parameters:
          api_token:
            description: Styra API Token
            type: string
            default: undefined
        steps:
          - run: echo "Running Check"
          - run: styra-cli configure -i test.styra.com -t <<parameters.api_token>>
          - run: ls -al
          - run: styra-cli get tokens
          - run: styra-cli validate check-local -r .

    jobs:
      check:
        executor: cli
        steps:
          - checkout # check out the code in the project directory
          - cli-check


workflows:
  workflow:
    jobs:
    - styra-orb/check
      # context: test 
