version: 2.1

description: orb test
orbs:
  styra-orb:
    executors:
      cli:
        docker:
          - image: styra/cli
    commands:
      check:
        steps:
          - run: echo "Running Check"
          - run:
            name: Configure
            command: styra-cli configure -i test.styra.com -t ${TOKEN}
          - run:
            name: Check-files
            command: ls -al
          - run:
            name: Check-styra
            command: styra-cli get tokens
          - run:
            name: Validate
            command: styra-cli validate check-local -r .

jobs:
  build:
    executor: cli
    steps:
    - checkout # check out the code in the project directory
    - check


workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: test 
